NUMPY





In [ ]:
# NumPy-"Numerical Python", is a fundamental Python library for numerical and scientific computing.
# It provides support for working with large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays efficiently.

In [ ]:
import numpy as np

In [ ]:
np.__version__  #to know what is the version of numpy

'1.22.4'

In [ ]:
l1=[i for i in range(10)]
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(l1)

list

In [ ]:
a=np.array(l1)  #to convert a list into numpy array

In [ ]:
a.shape  #if nothing is present after then we have to assume 1

(10,)

In [ ]:
np.array([1,2,3,4],dtype='float')  #datatype converting from integer to float, enclose with np.array

array([1., 2., 3., 4.])

In [ ]:
 a=np.array([[2,3,4,5],[6,7,8,9],[10,11,12,13]]) #matrix 3,4 consider list as a row

In [ ]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a #3 rows-list,columns-no.of elements in the list

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
np.zeros(10) #vector of shape 10*1 with all zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,5),dtype=float) #mention shape of array,datatype

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(100,1000,10) #generate num b/w 0&1, total num we want 5 #diff b/w any 2num the diff is same for linspace

array([ 100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,  900.,
       1000.])

In [ ]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
#numpy to create random values,shape
np.random.random((3,3))

array([[0.42117503, 0.75725099, 0.27434254],
       [0.3010046 , 0.64452811, 0.69179968],
       [0.09478639, 0.22920121, 0.68263659]])

In [ ]:
#create random values from a normal districbution
np.random.normal(0,1,(3,3)) #mean,standard deviation,shape

array([[-1.05532684, -0.35283821,  2.30201259],
       [ 0.0315952 , -1.57220172,  0.05803991],
       [-0.80215417, -1.13949226, -0.31322845]])

In [ ]:
#if you want to create random intergers
np.random.randint(0,20,(3,3)) # startvalue,endvalue,shape #exception

array([[18,  7, 19],
       [ 3,  7,  9],
       [ 6, 15,  3]])

In [ ]:
np.eye(3,3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(2,dtype=np.int8)

array([[1, 0],
       [0, 1]], dtype=int8)

In [ ]:
x1 = np.random.randint(10,size=6)
x1

array([6, 6, 4, 6, 5, 4])

In [ ]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[9, 5, 5, 5],
       [2, 0, 3, 7],
       [5, 3, 8, 8]])

In [ ]:
x3 = np.random.randint(10,size=(3,4,5))
x3

array([[[2, 5, 2, 9, 0],
        [2, 7, 9, 1, 2],
        [0, 0, 5, 3, 0],
        [3, 0, 2, 0, 5]],

       [[4, 5, 6, 2, 0],
        [6, 4, 0, 8, 0],
        [2, 8, 3, 1, 1],
        [6, 0, 4, 8, 3]],

       [[6, 9, 4, 0, 4],
        [1, 2, 0, 6, 7],
        [1, 8, 9, 2, 8],
        [3, 7, 4, 6, 4]]])

In [ ]:
x3.ndim  #to find the dimension

3

In [ ]:
x3.size

60

In [ ]:
x1[0]  # to axis first element

6

In [ ]:
x1[-1]  #to access last element

4

In [ ]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[5, 6, 6, 1],
       [1, 7, 5, 1],
       [8, 1, 6, 7]])

In [ ]:
x2[0,0]

5

In [ ]:
#first row second element
x2[0,1]

6

In [ ]:
x2[0,0]=12 #to change first element
x2

array([[12,  6,  6,  1],
       [ 1,  7,  5,  1],
       [ 8,  1,  6,  7]])

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
x2

array([[12,  6,  6,  1],
       [ 1,  7,  5,  1],
       [ 8,  1,  6,  7]])

In [ ]:
x2[:2,:2] #rowposition,column position first2rows & 2cols

array([[12,  6],
       [ 1,  7]])

In [ ]:
x2[1:2,:2] #second row

array([[1, 7]])

In [ ]:
x2[:2,1:2] #second col

array([[6],
       [7]])

In [ ]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
len(a)

9

In [ ]:
a=a.reshape(3,3) #reshape the list into matrix
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
y=a[np.newaxis,:] #(dimension,rows,cols)
y.shape

(1, 3, 3)

In [ ]:
y=a[:,np.newaxis] #(dimension,rows,cols)
y.shape

(3, 1, 3)

In [ ]:
y=a[:,:,np.newaxis] #(dimension,rows,cols)
y.shape

(3, 3, 1)

In [ ]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [ ]:
x.shape

(3,)

In [ ]:
y.shape

(3,)

In [ ]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [ ]:
#allows you to indicate the row and column positioning in its parameter list
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
grid.shape

(2, 3)

In [ ]:
grid=grid[np.newaxis,:,:]

In [ ]:
grid.shape

(1, 2, 3)

In [ ]:
np.concatenate((grid,grid),axis=0) #conc along axis 0

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
np.concatenate((grid,grid),axis=0).shape

(2, 2, 3)

In [ ]:
np.concatenate((grid,grid),axis=1)

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [ ]:
np.concatenate((grid,grid),axis=1).shape

(1, 4, 3)

In [ ]:
np.concatenate((grid,grid),axis=2)

array([[[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]]])

In [ ]:
np.concatenate((grid,grid),axis=2).shape

(1, 2, 6)

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[0,7,6,7]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
n=np.arange(8)
n

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
n.shape

(8,)

In [ ]:
n=n.reshape(2,4)
n

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
n.shape

(2, 4)

In [ ]:
d=n[np.newaxis,:]
d.shape

(1, 2, 4)

In [ ]:
d

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
d=n[:,np.newaxis]
d.shape

(2, 1, 4)

In [ ]:
d

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]]])

In [ ]:
s=np.array([7,4,5,6])
p=np.array([3,1,2,8])

In [ ]:
np.concatenate((s,p))

array([7, 4, 5, 6, 3, 1, 2, 8])

In [ ]:
x=np.array([1,2,3])
grid=np.array([[7,8,9],
               [5,6,4]])

In [ ]:
x.shape

(3,)

In [ ]:
grid.shape

(2, 3)

In [ ]:
np.vstack([x,grid])

array([[1, 2, 3],
       [7, 8, 9],
       [5, 6, 4]])

In [ ]:
x=np.array([[99],[99]])
x.shape

(2, 1)

In [ ]:
np.hstack([x,grid])

array([[99,  7,  8,  9],
       [99,  5,  6,  4]])

In [ ]:
g=np.array([3,4,5,6])
g[::-1]

array([6, 5, 4, 3])

In [ ]:
x=np.arange(5)
x+5

array([5, 6, 7, 8, 9])

In [ ]:
np.add(x,5)

array([5, 6, 7, 8, 9])

In [ ]:
w=x-5
w

array([-5, -4, -3, -2, -1])

In [ ]:
x*5

array([ 0,  5, 10, 15, 20])

In [ ]:
np.abs(w)

array([5, 4, 3, 2, 1])

In [ ]:
t=np.linspace(0,np.pi,3)

In [ ]:
t

array([0.        , 1.57079633, 3.14159265])

In [ ]:
np.exp(t)

array([ 1.        ,  4.81047738, 23.14069263])

In [ ]:
import numpy as np

In [ ]:
#bradcasting-the col gets replicated and add te matrix with vector(col+col)
a = np.array([0,1,2])
b = np.array([5,5,5])
a+b

array([5, 6, 7])

In [ ]:
M=np.ones((3,3))

In [ ]:
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
#path
X=np.random.random((10,3))

In [ ]:
Xmean=np.mean(X)
Xmean

0.47187744739957577

In [ ]:
Xcentered=X-Xmean #subtract meanfrom every value

In [ ]:
Xcentered/np.std(X) #all the data ppoits b/w 0&1, there is a chance that the data points can lie b/w -1&1

array([[-0.50477525, -0.9539919 , -1.34567182],
       [ 0.4471732 , -0.31217709, -1.06390323],
       [-0.2566817 ,  1.69547452, -1.16461668],
       [-0.71966965,  0.6903446 ,  0.03829187],
       [-1.68664542,  1.46352443,  0.37037887],
       [ 0.28700702,  1.53259002, -1.27846074],
       [ 1.50145174,  1.17761019, -0.32139479],
       [-0.79707658, -1.16223415,  1.50543474],
       [-0.46250637,  1.03028055,  0.03871221],
       [ 1.16772647, -0.62478156, -0.29141352]])

In [ ]:
X_final=Xcentered/np.std(X)

In [ ]:
X_final.mean()

-1.7393494052460786e-16

In [ ]:
import pandas as pd
df=pd.read_csv("/content/president_heights (2).csv")

In [ ]:
df.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [ ]:
height=df['height(cm)'].values

In [ ]:
height

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185, 191, 182])

In [ ]:
height>100

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
height[height>100].mean()

180.04545454545453

In [ ]:
height[height>180].mean()

185.33333333333334

In [ ]:
height[(height>180)&(height<185)].mean()

182.6153846153846

In [ ]:
height[~((height>180)&(height<185))].mean()

178.96774193548387

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'1.5.3'

In [ ]:
data=pd.Series([0.25,0.5,0.75,1])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
even_list=[i for i in range(100) if i%2==0]

In [ ]:
pd.Series(even_list)

0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
11    22
12    24
13    26
14    28
15    30
16    32
17    34
18    36
19    38
20    40
21    42
22    44
23    46
24    48
25    50
26    52
27    54
28    56
29    58
30    60
31    62
32    64
33    66
34    68
35    70
36    72
37    74
38    76
39    78
40    80
41    82
42    84
43    86
44    88
45    90
46    92
47    94
48    96
49    98
dtype: int64

In [ ]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
data=pd.Series([0,0.25,0.5,1],index=['a','b','c','d'])
data

a    0.00
b    0.25
c    0.50
d    1.00
dtype: float64

In [ ]:
data['c']

0.5

In [ ]:
import numpy as np

a=np.random.randint(0,10,size=(6))

In [ ]:
a

array([4, 7, 3, 4, 0, 2])

In [ ]:
pd.Series(a,index=[1,2,3,'a','b','c'])

1    4
2    7
3    3
a    4
b    0
c    2
dtype: int64

In [ ]:
dict1={'Ap':1000,'TS':20000,'KA':3000,'TN':40000}
ser=pd.Series(dict1)

In [ ]:
ser['TS':'TN']

TS    20000
KA     3000
TN    40000
dtype: int64

In [ ]:
ser[['TS','TN']]

TS    20000
TN    40000
dtype: int64

In [ ]:
dict1={'Ap':1000,'TS':2000,'KA':3000,'TN':4000}
area={'Ap':100,'KA':300,'TS':200,'TN':400}

df=pd.DataFrame({'dict1':dict1,'area':area})

In [ ]:
df

dict1  area
Ap   1000   100
TS   2000   200
KA   3000   300
TN   4000   400

In [ ]:
df.values

array([[1000,  100],
       [2000,  200],
       [3000,  300],
       [4000,  400]])

In [ ]:
df.index

Index(['Ap', 'TS', 'KA', 'TN'], dtype='object')

In [ ]:
df.columns

Index(['dict1', 'area'], dtype='object')

In [ ]:
df['dict1']

Ap    1000
TS    2000
KA    3000
TN    4000
Name: dict1, dtype: int64

In [ ]:
dict1=[{'a':1,'b':2},{'c':3,'d':4}]

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [ ]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [ ]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [ ]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [ ]:
data.fillna(value=np.mean(data))

a    1.0
b    2.0
c    2.0
d    2.0
e    3.0
dtype: float64

#Hierrachial indexing

In [ ]:
index = [('California', 2000),('California', 2001), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

In [ ]:
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561,1234567]

In [ ]:
pd.Series(populations,index=index)

(California, 2000)    33871648
(California, 2001)    37253956
(California, 2010)    18976457
(New York, 2000)      19378102
(New York, 2010)      20851820
(Texas, 2000)         25145561
(Texas, 2010)          1234567
dtype: int64

In [ ]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2001),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [ ]:
df1 = pd.DataFrame(np.random.rand(2,2),index=[1,2],columns=['A','B'])
df1

A         B
1  0.817132  0.643944
2  0.595838  0.295566

In [ ]:
index=[[2013,2014],[1,2]]
index=pd.MultiIndex.from_product(index,names=['year','visit'])
print(index)
columns=pd.MultiIndex.from_product([['bob','john','ram'],['HeartRate','Temp']],names=['subject','type'])
print(index)
data=np.random.randn(4,6)
print(data)
health_data=pd.DataFrame(data,index=index,columns=columns)
health_data

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])
MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])
[[-0.81683286 -2.18594593  0.06208422 -1.03875452 -0.61766167  1.58050575]
 [ 1.04974936 -0.63022874 -2.02642916  0.6221917  -0.49392975  1.48235347]
 [-0.42133864 -0.39195492 -0.92729421 -1.26087903  0.53276134 -0.67422208]
 [ 0.04592762  0.14160085  0.31186913  0.06765396  0.61870167 -0.38520096]]


subject          bob                john                 ram          
type       HeartRate      Temp HeartRate      Temp HeartRate      Temp
year visit                                                            
2013 1     -0.816833 -2.185946  0.062084 -1.038755 -0.617662  1.580506
     2      1.049749 -0.630229 -2.026429  0.622192 -0.493930  1.482353
2014 1     -0.421339 -0.391955 -0.927294 -1.260879  0.532761 -0.674222
     2      0.045928  0.141601  0.311869  0.067654  0.618702 -0.385201

In [ ]:
index=[[2013,2014],[1,2],[3,5]]
index=pd.MultiIndex.from_product(index,names=['year','visit','roomnumber'])
print(index)
columns=pd.MultiIndex.from_product([['bob','john','ram'],['HeartRate','Temp']],names=['subject','type'])
print(index)
data=np.random.randn(8,6)
print(data)
health_data=pd.DataFrame(data,index=index,columns=columns)
health_data

MultiIndex([(2013, 1, 3),
            (2013, 1, 5),
            (2013, 2, 3),
            (2013, 2, 5),
            (2014, 1, 3),
            (2014, 1, 5),
            (2014, 2, 3),
            (2014, 2, 5)],
           names=['year', 'visit', 'roomnumber'])
MultiIndex([(2013, 1, 3),
            (2013, 1, 5),
            (2013, 2, 3),
            (2013, 2, 5),
            (2014, 1, 3),
            (2014, 1, 5),
            (2014, 2, 3),
            (2014, 2, 5)],
           names=['year', 'visit', 'roomnumber'])
[[-0.48734089 -1.73465592  1.33286492 -0.14546876 -1.07242475  0.28301725]
 [ 0.79194567 -0.66431944  0.54726748  1.22873547  0.79319196 -0.37992766]
 [ 0.26488428  0.76133001  1.12160466  0.1647399  -0.20624687 -1.31551922]
 [ 0.14157664  0.86691241 -0.35098608 -0.73649851 -0.41353817 -0.54671401]
 [-0.09905449 -0.26569702  0.56550941 -1.60512226  0.63447003 -0.90113159]
 [-0.07642375  1.34383633 -0.65875898 -0.03206918  1.09915894  0.87313838]
 [ 1.23207205 -0.21724166 -1.486

subject                     bob                john                 ram  \
type                  HeartRate      Temp HeartRate      Temp HeartRate   
year visit roomnumber                                                     
2013 1     3          -0.487341 -1.734656  1.332865 -0.145469 -1.072425   
           5           0.791946 -0.664319  0.547267  1.228735  0.793192   
     2     3           0.264884  0.761330  1.121605  0.164740 -0.206247   
           5           0.141577  0.866912 -0.350986 -0.736499 -0.413538   
2014 1     3          -0.099054 -0.265697  0.565509 -1.605122  0.634470   
           5          -0.076424  1.343836 -0.658759 -0.032069  1.099159   
     2     3           1.232072 -0.217242 -1.486682 -2.306465 -0.420145   
           5           0.422419  1.188613  0.776866 -0.030216  1.226422   

subject                          
type                       Temp  
year visit roomnumber            
2013 1     3           0.283017  
           5          -0.379928  
     2     3          -1.315519  
           5          -0.546714  
2014 1     3          -0.901132  
           5           0.873138  
     2     3           0.071342  
           5           0.276335

In [ ]:
health_data.mean(axis=1,level='subject')

<ipython-input-32-5dbe9897eb8c>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  health_data.mean(axis=1,level='subject')


subject                     bob      john       ram
year visit roomnumber                              
2013 1     3          -1.110998  0.593698 -0.394704
           5           0.063813  0.888001  0.206632
     2     3           0.513107  0.643172 -0.760883
           5           0.504245 -0.543742 -0.480126
2014 1     3          -0.182376 -0.519806 -0.133331
           5           0.633706 -0.345414  0.986149
     2     3           0.507415 -1.896573 -0.174401
           5           0.805516  0.373325  0.751378

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df1 = pd.DataFrame(np.random.rand(2,2),index=[1,2],columns=['A','B'])
df2 = pd.DataFrame(np.random.rand(2,2),index=[3,4],columns=['A','B'])

In [ ]:
df1

A         B
1  0.681123  0.019564
2  0.858233  0.155207

In [ ]:
df2

A         B
3  0.225741  0.517483
4  0.290170  0.921640

In [ ]:
pd.concat([df1,df2])

A         B
1  0.681123  0.019564
2  0.858233  0.155207
3  0.225741  0.517483
4  0.290170  0.921640

In [ ]:
df1 = pd.DataFrame(np.random.rand(2,2),index=[1,2],columns=['A','B'])
df2 = pd.DataFrame(np.random.rand(4,5),index=[1,2,3,4],columns=['C','D','E','F','G'])

In [ ]:
df1

A         B
1  0.262185  0.424429
2  0.376463  0.055174

In [ ]:
df2

C         D         E         F         G
1  0.211012  0.563399  0.992234  0.505840  0.826854
2  0.802969  0.112273  0.902500  0.579233  0.252836
3  0.615571  0.083141  0.068275  0.418374  0.539296
4  0.918545  0.302926  0.234916  0.134688  0.017910

In [ ]:
pd.concat([df1,df2])

A         B         C         D         E         F         G
1  0.262185  0.424429       NaN       NaN       NaN       NaN       NaN
2  0.376463  0.055174       NaN       NaN       NaN       NaN       NaN
1       NaN       NaN  0.211012  0.563399  0.992234  0.505840  0.826854
2       NaN       NaN  0.802969  0.112273  0.902500  0.579233  0.252836
3       NaN       NaN  0.615571  0.083141  0.068275  0.418374  0.539296
4       NaN       NaN  0.918545  0.302926  0.234916  0.134688  0.017910

In [ ]:
pd.concat([df1,df2],ignore_index=True)

A         B         C         D         E         F         G
0  0.262185  0.424429       NaN       NaN       NaN       NaN       NaN
1  0.376463  0.055174       NaN       NaN       NaN       NaN       NaN
2       NaN       NaN  0.211012  0.563399  0.992234  0.505840  0.826854
3       NaN       NaN  0.802969  0.112273  0.902500  0.579233  0.252836
4       NaN       NaN  0.615571  0.083141  0.068275  0.418374  0.539296
5       NaN       NaN  0.918545  0.302926  0.234916  0.134688  0.017910

In [ ]:
pd.concat([df1,df2],axis=1)

A         B         C         D         E         F         G
1  0.262185  0.424429  0.211012  0.563399  0.992234  0.505840  0.826854
2  0.376463  0.055174  0.802969  0.112273  0.902500  0.579233  0.252836
3       NaN       NaN  0.615571  0.083141  0.068275  0.418374  0.539296
4       NaN       NaN  0.918545  0.302926  0.234916  0.134688  0.017910

In [ ]:
#Explanation of the topics-
# time series(finance sets)-stock market,forecast
# text data(big space,nlp-domain)-concepts of sentiment analysis,q/a,summarizing(chatgpt),entity classification...etc
# image data(nlp-natural language processing)-computer vision,image generation,object detection,self driving cars
# reccomendation systems-google search,insta,snap,flipkart,wallmart etc,(seperate learning path)

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic=sns.load_dataset('titanic')

In [ ]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
titanic.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [ ]:
titanic.groupby(['sex','class']).aggregate({'survived':np.mean})

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [ ]:
titanic.pivot_table('survived',index='sex',columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
titanic.pivot_table('survived',index=['sex','age'],columns='class')

class         First  Second  Third
sex    age                        
female 0.75     NaN     NaN   1.00
       1.00     NaN     NaN   1.00
       2.00     0.0     1.0   0.25
       3.00     NaN     1.0   0.00
       4.00     NaN     1.0   1.00
...             ...     ...    ...
male   70.00    0.0     0.0    NaN
       70.50    NaN     NaN   0.00
       71.00    0.0     NaN    NaN
       74.00    NaN     NaN   0.00
       80.00    1.0     NaN    NaN

[145 rows x 3 columns]

In [ ]:
titanic.pivot_table(index='sex',columns='class',aggfunc={'survived':np.sum})

survived             
class     First Second Third
sex                         
female       91     70    72
male         45     17    47